name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -sL --retry 3 "https://salao-pink-fashion-fuaxsmfhsm84gd52m8zj7p.streamlit.app/" -o /dev/null || true
